run-hello-world:
	nvcc -arch=sm_75 -o hello-world hello_world.cu -run

run-loop-accelerate:
	nvcc -arch=sm_75 -o loop-accelerate loop_accelerate.cu -run

run-coordinating-parallel:
	nvcc -arch=sm_75 -o coordinating-parallel coordinating_parallel.cu -run

run-memory101:
	nvcc -arch=sm_75 -o memory101 memory101.cu -run

run-mismatched-config:
	nvcc -arch=sm_75 -o mismatched-config mismatched_config.cu -run

run-grid-stride:
	nvcc -arch=sm_75 -o grid_stride grid_stride.cu -run

run-error101:
	nvcc -arch=sm_75 -o error101 error101.cu -run

run-vector-add:
	nvcc -arch=sm_75 -o vector-add vector_add.cu -run

run-matrix-mul:
	nvcc -arch=sm_75 -o matrix-mul matrix_mul.cu -run
