run-hello-world:
	nvcc -arch=sm_75 -o hello-world hello_world.cu -run

run-loop-accelerate:
	nvcc -arch=sm_75 -o loop-accelerate loop_accelerate.cu -run

run-coordinating-parallel:
	nvcc -arch=sm_75 -o coordinating-parallel coordinating_parallel.cu -run
